from Foundation.Group import Group

class GroupUIStore(Group):
    Category = "Resources"

    def _getLayerParams(self):
        params = { "Size" : (2736,1536), "Type" : "Layer2D", "Name" : "Layer2D_Main", "Main" : True }
        return params
        pass

    def _onLoader(self):
        self.createLayer( "Layer2D_Main", Type = "Layer2D", Size = (2736, 1536), Main = True )
        self.addPrototype( "Movie2", Name = "Movie2_PopUpBackground_Normal" , ResourceMovie = "Movie2_UIStore", CompositionName = "PopUpBackground_Normal"  )
        self.addPrototype( "Movie2", Name = "Movie2_PopUpBackground_Big" , ResourceMovie = "Movie2_UIStore", CompositionName = "PopUpBackground_Big"  )
        self.addPrototype( "Movie2Button", Name = "Movie2Button_PopUpButton", ResourceMovie = "Movie2_UIStore", CompositionNameIdle = "PopUpButton_Idle", CompositionNameAppear = "PopUpButton_Appear", CompositionNameEnter = "PopUpButton_Enter", CompositionNameOver = "PopUpButton_Over", CompositionNameLeave = "PopUpButton_Leave", CompositionNamePush = "PopUpButton_Push", CompositionNamePressed = "PopUpButton_Pressed", CompositionNameRelease = "PopUpButton_Release", CompositionNameClick = "PopUpButton_Click", CompositionNameBlock = "PopUpButton_Block", CompositionNameBlockEnter = "PopUpButton_BlockEnter", CompositionNameBlockEnd = "PopUpButton_BlockEnd", CompositionNameSelected = "PopUpButton_Selected", CompositionNameSelectedEnter = "PopUpButton_SelectedEnter", CompositionNameSelectedEnd = "PopUpButton_SelectedEnd" )
        self.addPrototype( "Movie2Button", Name = "Movie2Button_Circle", ResourceMovie = "Movie2_UIStore", CompositionNameIdle = "Circle_Idle", CompositionNameAppear = "Circle_Appear", CompositionNameEnter = "Circle_Enter", CompositionNameOver = "Circle_Over", CompositionNameLeave = "Circle_Leave", CompositionNamePush = "Circle_Push", CompositionNamePressed = "Circle_Pressed", CompositionNameRelease = "Circle_Release", CompositionNameClick = "Circle_Click", CompositionNameBlock = "Circle_Block", CompositionNameBlockEnter = "Circle_BlockEnter", CompositionNameBlockEnd = "Circle_BlockEnd", CompositionNameSelected = "Circle_Selected", CompositionNameSelectedEnter = "Circle_SelectedEnter", CompositionNameSelectedEnd = "Circle_SelectedEnd" )
        self.addPrototype( "Movie2Button", Name = "Movie2Button_Rectangle", ResourceMovie = "Movie2_UIStore", CompositionNameIdle = "Rectangle_Idle", CompositionNameAppear = "Rectangle_Appear", CompositionNameEnter = "Rectangle_Enter", CompositionNameOver = "Rectangle_Over", CompositionNameLeave = "Rectangle_Leave", CompositionNamePush = "Rectangle_Push", CompositionNamePressed = "Rectangle_Pressed", CompositionNameRelease = "Rectangle_Release", CompositionNameClick = "Rectangle_Click", CompositionNameBlock = "Rectangle_Block", CompositionNameBlockEnter = "Rectangle_BlockEnter", CompositionNameBlockEnd = "Rectangle_BlockEnd", CompositionNameSelected = "Rectangle_Selected", CompositionNameSelectedEnter = "Rectangle_SelectedEnter", CompositionNameSelectedEnd = "Rectangle_SelectedEnd" )
        self.addPrototype( "Movie2Button", Name = "Movie2Button_Rectangle_Green", ResourceMovie = "Movie2_UIStore", CompositionNameIdle = "Rectangle_Green_Idle", CompositionNameAppear = "Rectangle_Green_Appear", CompositionNameEnter = "Rectangle_Green_Enter", CompositionNameOver = "Rectangle_Green_Over", CompositionNameLeave = "Rectangle_Green_Leave", CompositionNamePush = "Rectangle_Green_Push", CompositionNamePressed = "Rectangle_Green_Pressed", CompositionNameRelease = "Rectangle_Green_Release", CompositionNameClick = "Rectangle_Green_Click", CompositionNameBlock = "Rectangle_Green_Block", CompositionNameBlockEnter = "Rectangle_Green_BlockEnter", CompositionNameBlockEnd = "Rectangle_Green_BlockEnd", CompositionNameSelected = "Rectangle_Green_Selected", CompositionNameSelectedEnter = "Rectangle_Green_SelectedEnter", CompositionNameSelectedEnd = "Rectangle_Green_SelectedEnd" )
        self.addPrototype( "Movie2CheckBox", Name = "Movie2Checkbox_Circle", ResourceMovie = "Movie2_UIStore", CompositionNameTrue_Idle = "Circle_True_Idle", CompositionNameTrue_Enter = "Circle_True_Enter", CompositionNameTrue_Over = "Circle_True_Over", CompositionNameTrue_Click = "Circle_True_Click", CompositionNameTrue_Leave = "Circle_True_Leave", CompositionNameTrue_Push = "Circle_True_Push", CompositionNameTrue_Pressed = "Circle_True_Pressed", CompositionNameTrue_Release = "Circle_True_Release", CompositionNameFalse_Idle = "Circle_False_Idle", CompositionNameFalse_Enter = "Circle_False_Enter", CompositionNameFalse_Over = "Circle_False_Over", CompositionNameFalse_Click = "Circle_False_Click", CompositionNameFalse_Leave = "Circle_False_Leave", CompositionNameFalse_Push = "Circle_False_Push", CompositionNameFalse_Pressed = "Circle_False_Pressed", CompositionNameFalse_Release = "Circle_False_Release" )
        self.addPrototype( "Movie2", Name = "Movie2_Circle" , ResourceMovie = "Movie2_UIStore", CompositionName = "Circle"  )
        self.addPrototype( "Movie2", Name = "Movie2_Circle_S" , ResourceMovie = "Movie2_UIStore", CompositionName = "Circle_S"  )
        self.addPrototype( "Movie2", Name = "Movie2_Build_Version" , ResourceMovie = "Movie2_UIStore", CompositionName = "Build_Version"  )
        self.addPrototype( "Movie2", Name = "Movie2_Text" , ResourceMovie = "Movie2_UIStore", CompositionName = "Text"  )
        self.addPrototype( "Movie2", Name = "Movie2_MissClickEffect" , ResourceMovie = "Movie2_UIStore", CompositionName = "MissClickEffect"  )
        self.addPrototype( "Movie2", Name = "Movie2_Square" , ResourceMovie = "Movie2_UIStore", CompositionName = "Square"  )
        self.addPrototype( "Movie2", Name = "Movie2_HintCounter" , ResourceMovie = "Movie2_UIStore", CompositionName = "HintCounter"  )
        self.addPrototype( "Movie2", Name = "Movie2_SearchItemsCorner_Left" , ResourceMovie = "Movie2_UIStore", CompositionName = "SearchItemsCorner_Left"  )
        self.addPrototype( "Movie2", Name = "Movie2_SearchItemsCorner_Right" , ResourceMovie = "Movie2_UIStore", CompositionName = "SearchItemsCorner_Right"  )
        self.addPrototype( "Movie2", Name = "Movie2_HeaderLivesBackground" , ResourceMovie = "Movie2_UIStore", CompositionName = "HeaderLivesBackground"  )
        self.addPrototype( "Movie2ProgressBar", Name = "Movie2ProgressBar_Loading", ResourceMovie = "Movie2_UIStore", CompositionNameIdle = "Loading_Idle", CompositionNameOver = "Loading_Over", CompositionNameProgress = "Loading_Progress", CompositionNameBlock = "Loading_Block", CompositionNameFullProgress = "Loading_FullProgress", CompositionNameHolder = "Loading_Holder" )
        self.addPrototype( "Movie2Button", Name = "Movie2Button_Square_256", ResourceMovie = "Movie2_UIStore", CompositionNameIdle = "Square_256_Idle", CompositionNameAppear = "Square_256_Appear", CompositionNameEnter = "Square_256_Enter", CompositionNameOver = "Square_256_Over", CompositionNameLeave = "Square_256_Leave", CompositionNamePush = "Square_256_Push", CompositionNamePressed = "Square_256_Pressed", CompositionNameRelease = "Square_256_Release", CompositionNameClick = "Square_256_Click", CompositionNameBlock = "Square_256_Block", CompositionNameBlockEnter = "Square_256_BlockEnter", CompositionNameBlockEnd = "Square_256_BlockEnd", CompositionNameSelected = "Square_256_Selected", CompositionNameSelectedEnter = "Square_256_SelectedEnter", CompositionNameSelectedEnd = "Square_256_SelectedEnd" )
        pass
    pass
